### PR TITLE
Health Check and volume change

### PR DESCRIPTION
**Pull request by djaydev**
The health check only checks for port 5053 but the Dockerfile/Entrypoint allows you to use a custom port.  Changing the port makes the health check fail.

Creating a VOLUME in the dockerfile and copying a file to it in the entrypoint tells docker to create a volume on the local file system with that file, instead of just using the file that's already in the docker image.  Every time you rebuild the container for an update or any other reason a new volume folder is created on the file system with a new config file in it.  I didn't realize it until I had 18 volumes created.  If the user wants to use a custom TOML file then they can still map it in the docker run command.  Since the main two config edits can be done with variables I think most won't need a static TOML file.  But if they do it's still possible and this edit doesn't change the process the user needs to do for the custom TOML file.

This definitely isn't a final version just an initial draft proposal we can edit to improve the container.  I'd love to collab and brainstorm on this with you.

### CODE REVIEW

**Comment by djaydev** [comment]
Additionally, if you want to keep the ability to change the address from 0.0.0.0 to something else we can do another ENV variable for DNSCRYPT_LISTEN_ADDRESS=0.0.0.0 with the entrypoint.sh sed to 
`sed -r "s/^(# )?(listen_addresses = ).+$/\2${['DNSCRYPT_LISTEN_ADDRESS}:${DNSCRYPT_LISTEN_PORT}']/"`

For allowing additional binary options at the end of `exec dnscrypt-proxy -config ` I believe we should move the execution outside of the entrypoint.sh and put into the Dockerfile.  I can provide an example if you prefer that method.

**Comment by klutchell** [comment]
I'd like to see that example because I prefer to have the binary exposed for advanced runtime flags outside the config file.
Like if someone want's to change the verbosity or point to a custom config file path the easiest was is with those flags. I already confirmed that providing `-config` more than once to the same binary call will respect the last value.

I also prefer to keep an unmodified copy of the example config in /app. That's why I was copying it rather than changing it in place and pointing to it directly. If someone is using a custom config volume it would be nice if they could still copy or refer to the unmodified example config file. Maybe we should just remove the VOLUME command from the Dockerfile so it's not created unless a user wants it.

**Comment by djaydev** [comment]
> 
> 
> I'd like to see that example because I prefer to have the binary exposed for advanced runtime flags outside the config file.
> Like if someone want's to change the verbosity or point to a custom config file path the easiest was is with those flags. I already confirmed that providing `-config` more than once to the same binary call will respect the last value.
>
In the entrypoint.sh I left the possibility for a custom script if it's at /config/dnscrypt-proxy.toml it will use that instead of /app/.toml file.  If the user wants to use a custom config file that's not at /config, for example /customTOMLS/accountingDNS.toml, then they would have to specify that as a CMD during runtime.
`docker run -d -v /appdata/customTOMLS:/customTOMLS klutchell/dnscrypt-proxy -config /customTOMLS/accountingDNS.toml`
I would have to add the $@ at the very end of the entrypoint.sh for it to grab the runtime arguments.

> 
> I also prefer to keep an unmodified copy of the example config in /app. That's why I was copying it rather than changing it in place and pointing to it directly. If someone is using a custom config volume it would be nice if they could still copy or refer to the unmodified example config file. Maybe we should just remove the VOLUME command from the Dockerfile so it's not created unless a user wants it.
>
If they are using a custom config file at /config/dnscrypt-proxy.toml then the original /app/.toml file won't be modified.  It will be left intact for later inspection.  If they are using a custom config file outside of /config folder, I'm not sure that entrypoint is even required for that kind of user.  They should specify they're own entrypoint that starts dnscrypt.  They will most likely edit all the entries that the entrypoint.sh does.
`docker run -d --entrypoint='exec dnscrypt-proxy -config /customTOMLS/accountingDNS.toml' -v /appdata/customTOMLS:/customTOMLS klutchell/dnscrypt-proxy`

Let me know if I missed anything or my theory is off.

**Comment by klutchell** [comment]
I agree with some of these changes.

1. Updating the port in HEALTHCHECK is convenient, but not critical since if a user specifies a custom port they can also specify a custom healthcheck... still nice to have though and users will not likely want to bind to anything other than 0.0.0.0 so we should keep this change.

2. I agree we should remove the VOLUME line from the Dockerfile. No need to create a bunch of volumes on the user system.

However I think we should keep the `$@` in the entrypoint for custom runtime commands, like `-help` and `-version` (or even `-config` if they have multiple config files with different names and want to switch between them.

I also think we should always copy the default .toml from /app to /config if it doesn't already exist by that name. Even if the user is overriding the -config flag with their own value, I want to make sure there is always something sane in the /config dir on startup.
The use case is running with a bind mount for the first time, the config dir would be empty and doesn't give the user a helpful starting point for configuration.

**Comment by djaydev** [comment]
I'm with you however you want to do it, all suggestions :)

1. Changing the healthcheck at startup is a good option as well.  I would just suggest to mention it in the README that if you set a custom port to also add a healthcheck to your docker run command.  I'm not even sure how to do that.

2. Yea I'm with you, it's not only a new volume directory everytime but also a new .toml file inside it.  We're only talking 15.8KB per run, but still hehe.

I will definitely add the $@ back to the entrypoint.sh script.  I run this as set it and forget I never even considered that the app has these flags that are very useful.  I'm glad you mentioned that.

I've added the function to check if a default .toml file is located at /config, and if not, to create the /config directory and to copy the default .toml file to the newly created /config directory.  This only adds 15.8KB to the container size so it's not noticeable.

Just for my curiosity, what does it mean "running with a bind mount for the first time, the config dir would be empty and doesn't give the user a helpful starting point for configuration" ?

**Comment by klutchell** [comment]
> Just for my curiosity, what does it mean "running with a bind mount for the first time, the config dir would be empty and doesn't give the user a helpful starting point for configuration" ?

What I mean by this is if a user provides `-v /path/to/config:/config` as part of docker run, there's a chance the config dir they provided is empty. Unless they already had a config .toml from a previous installation or copied one from elsewhere. The intent of the `entrypoint.sh` script is to make sure they have an example config file to work with.

> I would just suggest to mention it in the README that if you set a custom port to also add a healthcheck to your docker run command.

I think I would like to avoid having users change the bind port inside the container. I'll document this edge case since a custom config would likely be using the wrong port - but if the average user wants to bind to a different port on the host they should use `-p <custom port>:5053/udp` at runtime and not change the 5053.

I'll push some changes this week to cover these cases and you can let me know what you think.

**Comment by djaydev** [comment]
Thank you for the explanation I know what you mean now.  The latest change I made to the enntrypoint.sh file 100% addresses that concern, as well as still addressing the concern about custom config files and maintaining the original /app/example-dnscrypt-proxy.toml.

I really liked the custom port option you have, because it's the only way to set the port outside of bridge docker networking type (-p only works for bridge networks).  If you use host networking or macvlan networking you're stuck with the hardcoded port.  

Up to you of course just my humble opinion.

**Comment by klutchell** [comment]
Ah, I see your use case now. I've just pushed a change that should address this as well as your other concerns regarding volumes and host networking.

I also provided more examples on the README, including one that I think covers your use case of host networking with custom port binding.

```bash
# eg. bind directly to port 53 on the host without docker nat
docker run --network host -e "DNSCRYPT_LISTEN_ADDRESSES=['127.0.0.1:53']" --no-healthcheck klutchell/dnscrypt-proxy
```

I still chose not to expose customizing only the port, since a user that wants to change the bind port in the container for host networking might also want to be able to specify a range or specific address to bind to. Like in your case you may want to bind to `127.0.0.1:53` instead of `0.0.0.0:53` so that only localhost lookups can use your proxy.

Does this make sense and have I addressed your concerns? You brought up some very good points and I don't want to diminish your work by making the changes myself.

If you're happy with the changes I'll close this issue.

**Comment by djaydev** [comment]
That's pretty much wraps it up for me thank you for your time and energy into this!  Please close at your leisure. 

I like the idea of quick options like changing the port, or server name(s) and the like while not effecting the rest of the container like the awesome healthcheck. I tried to submit this PR in that manner. Looking back at it I guess it is a lot of changes at once. I should have submitted smaller changes first.
I see you listed on the README a custom healthcheck option `--healthcheck-cmd` is the whole line `docker run --network host -e "DNSCRYPT_LISTEN_ADDRESSES=['127.0.0.1:53']" --healthcheck-cmd="--interval=5s --timeout=3s --start-period=10s CMD drill -p 5053 cloudflare.com @127.0.0.1 || exit 1" klutchell/dnscrypt-proxy` ?  Right now the user would have to copy that healthcheck command from the Dockerfile or go without a healthcheck if port 5053 is already in use.

**Comment by klutchell** [comment]
If you want to keep using the healthcheck but change the bind port from 5053 to 53 I would do the following.

```bash
# eg. bind directly to port 53 on the host without docker nat
docker run \
--network host \
-e "DNSCRYPT_LISTEN_ADDRESSES=['127.0.0.1:53']" \
--healthcheck-cmd "drill -p 53 cloudflare.com @127.0.0.1 || exit 1" \
klutchell/dnscrypt-proxy
```

Notice how I just had to override the CMD part of the healthcheck, and the interval etc. stayed the same.

Cheers!

**Pull request closed without merging**
